# Exercise 1, Nico Ott, 4214197
Your first task is to implement a D2Q9 lattice which has the structure as given in Figure 1. It represents one
lattice element with its 8 neighbours and the rest channel in the center, so it is a 3x3 lattice with the numbering of the
channels for the center cell indicated. All cells on the boundary do have channels as well that are not drawn. Imagine
the lattice continued on the whole 2D plane. To be able to simulate an infinite plane we use the trick of periodic
boundary conditions, e.g. the cell sitting at the end of channel 1 of the center cell has itself a streaming channel to
the “east” direction that enters the cell at the end of channel 3 of the center cell from the “west” direction.

In [1]:
import numpy as np
import random
import time

#### 1. Implement a 15x10 lattice.

In [2]:
# One lattice has 9 channels
m = 10
n = 10
lattice = np.zeros([9,m,n])

In [3]:
#print(lattice)

#### 2. Allow each of the 9 channels of the 150 cells to be occupied by either 1 or 0 particles.

In [4]:
    def fill(lattice, k):
        """
        Fills the lattice with n particles
        """
        idx_c = random.sample(range(0,9), k)
        idx_m = random.sample(range(0,m), k)
        idx_n = random.sample(range(0,n), k)
        print(ind_c)
        for pos in range(n):
            lattice[pos]=1

In [5]:
    def fill_channel(lattice, c):
        """
        Fills the lattice with n particles
        """
        lattice[c] = 1

In [6]:
    def fill_channel_arange(lattice, c):
        """
        Fills the lattice with n particles
        """
        temp = np.arange(m*n)
        temp.shape = (m,n)
        lattice[c] = temp

In [7]:
fill_channel_arange(lattice, 6)

In [8]:
print(lattice)

[[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.  

#### 3. Set up periodic boundary conditions.

(if a particle hits an edge, it will continue at the other side)

In [9]:
def flow_step(lattice):
    """
    Channels transitions are simulated with numpy.roll().
    np.roll(x, 1, axis=0) --> x is rolled downwards
    np.roll(x,-1, axis=0) --> x is rolled upwards
    np.roll(x, 1, axis=1) --> x is rolled to the right
    np.roll(x,-1, axis=1) --> x is rolled to the left
    """
    return np.array([lattice[0],
                    np.roll(lattice[3],-1, axis=1),
                    np.roll(lattice[4], 1, axis=0),
                    np.roll(lattice[1], 1, axis=1),
                    np.roll(lattice[2],-1, axis=0),
                    np.roll(np.roll(lattice[7], 1, axis=0),-1, axis=1),
                    np.roll(np.roll(lattice[8], 1, axis=0), 1, axis=1),
                    np.roll(np.roll(lattice[5],-1, axis=0), 1, axis=1),
                    np.roll(np.roll(lattice[6],-1, axis=0),-1, axis=1)])

#### 4. In each timestep shift the particle occupying a channel to the cell the channel is pointing to and check the result:
    • There must be no particle lost or additional particles created, their number ist conserved.
    • There must be no more then 1 particle per channel.
    • The rest channel must be unchanged in its occupation number.
**Note:** You may use as an initial condition a random distribution of 0 and 1 as occupation numbers for the 9x150
channels. Carefully check if the periodic boundary conditions are implemented in the right way. To this end it is best
to create a pattern of which you know how it must look like after one streaming step. Take, e.g., in one column all
the east pointing channels occupied with 1 and leave all the rest zero. This column must stream through the lattice.

In [10]:
sim_steps = 3

for t in range(sim_steps):
    time_start = time.time()
    lattice = flow_step(lattice)
    time_end = time.time()
    print("Step {}: \n {} \n Step took {} seconds".format(t+1, lattice, time_end-time_start))

Step 1: 
 [[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.